--create database SENAI_PIZZARIAS_EXTRA

--USE	SENAI_PIZZARIAS_EXTRA

--TABELA DE CATEGORIAS
CREATE TABLE CATEGORIAS(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL,
	VALOR VARCHAR(100) NOT NULL
)

--TABELA DE PIZZARIAS
CREATE TABLE PIZZARIAS(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(250) NOT NULL,
	ENDERECO VARCHAR(250) NOT NULL,
	TELEFONE CHAR(13) NOT NULL,
	OPCAO_VEGANA BIT NOT NULL,
	ID_CATEGORIA INT FOREIGN KEY REFERENCES CATEGORIAS(ID),
)

--TABELA DE USUARIOS
CREATE TABLE USUARIOS(
	ID INT IDENTITY PRIMARY KEY,
	EMAIL VARCHAR(250) UNIQUE NOT NULL,
	SENHA VARCHAR(100) NOT NULL
)