USE SENAI_PIZZARIAS_EXTRA

-- SELECIONANDO TODAS AS CATEGORIAS
SELECT * FROM CATEGORIAS

-- SELECIONANDO TODAS AS PIZZARIAS
SELECT * FROM PIZZARIAS

-- SELECIONANDO TODOS OS USUARIOS
SELECT * FROM USUARIOS

-- SELECIONANDO TODAS AS PIZZARIAS COM SUAS RESPECTIVAS CATEGORIAS
SELECT * FROM 
PIZZARIAS INNER JOIN CATEGORIAS
ON PIZZARIAS.ID_CATEGORIA = CATEGORIAS.ID
